--- 
config:
  hostname: configServer
  image: xiaojie/config-microservice
  restart: always
  links:
    - discovery
  ports:
    - "8899:8899"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
discovery:
  image: xiaojie/discovery-microservice
  restart: always
  hostname: discovery
  ports:
    - "8761:8761"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
gateway:
  image: xiaojie/api-gateway-microservice
  restart: always
  hostname: gateway
  links:
    - discovery
    - config
    - user
    - rating
    - movie
  ports:
    - "10000:10000"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
movie:
  hostname: movie
  image: xiaojie/movie-microservice
  restart: always
  links:
    - discovery
    - config
  ports:
    - "9006:9006"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
rating:
  hostname: rating
  image: xiaojie/rating-microservice
  restart: always
  links:
    - discovery
    - config
  ports:
    - "9004:9004"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
user:
  hostname: user
  image: xiaojie/user-microservice
  restart: always
  links:
    - discovery
    - config
  ports:
      - "9001:9001"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
recommendation:
  hostname: recommendation
  image: xiaojie/recommendation-service
  links:
    - discovery
    - config
  ports:
      - "9009:9009"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
ui:
  hostname: ui
  image: xiaojie/ui-microservice
  restart: always
  links:
    - discovery
    - config
  ports:
    - "9002:9002"
  environment:
    - SPRING_PROFILES_ACTIVE=docker