spring:
  profiles:
    active: docker
---

spring:
  profiles: cloud
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: gateway-77.cfapps.io
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/

---

spring:
  profiles: docker
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
zuul:
  routes:
    ui:
      path: /ui/**
      service-id: ui
    user:
      path: /userinfo/**
      service-id: userinfo
    movie:
      path: /movie/**
      service-id: movie
    rating:
      path: /rating/**
      service-id: rating
    recommendation:
      path: /recommendation/**
      service-id: recommendation
